blog/urls.py
from django.urls import path
from . import views
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserListView

urlpatterns = [
        path('', PostListView.as_view() , name = 'home'), 
        path('post/<int:pk>/', PostDetailView.as_view() , name = 'post-detail'), 
        path('post/new/', PostCreateView.as_view(), name='post-create'),
        path('post/<int:pk>/update/', PostUpdateView.as_view() , name = 'post-update'), 
        path('post/<int:pk>/delete/', PostDeleteView.as_view() , name = 'post-delete'),
        path('about/', views.about),
        path('like/<int:post_id>/', views.like_post, name='like_post'),

]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_view
from blog import views as blog_view
from chat import views as chat_view
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_view.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('blog.urls')), 
    path('user/<str:username>', blog_view.UserListView.as_view(), name = 'user-posts'),
    path('my-profile/', user_view.profile, name='my_profile'),
    path('profile/<str:username>/', user_view.user_profile, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('follow/<str:username>/', user_view.follow_user, name='follow_user'),
    path('followers-following/<str:username>/', user_view.followers_following, name='followers_following'),
    path('notifications/', user_view.notifications, name='notifications'),
    path('chat/<int:user_id>/', chat_view.chat_view, name='chat'),
    path('chat/<int:conversation_id>/send_message/', chat_view.send_message, name='send_message'),
    path('chat/<int:conversation_id>/get_messages/', chat_view.get_messages, name='get_messages'),
    path('chats/', chat_view.chat_list_view, name='chat_list'),
    path('accounts/', include('allauth.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from blog import models as blog_models
from PIL import Image
# Create your models here.
class Profile(models.Model):
  user = models.OneToOneField(User, on_delete= models.CASCADE)
  image = models.ImageField(default='default.jpg', upload_to='profile_pics')
  bio = models.CharField(max_length=100, blank=True)
  def __str__(self):
  	return f'{self.user.username} Profile'

  def save(self, *args, **kwargs):
  	super(Profile, self).save(*args, **kwargs)

  	img = Image.open(self.image.path)
  	if img.height > 300 or img.width > 300:
  		output_size = (300,300)
  		img.thumbnail(output_size)
  		img.save(self.image.path)

class Follow(models.Model):
	follower = models.ForeignKey(User, related_name="following", on_delete=models.CASCADE)
	followed = models.ForeignKey(User, related_name="followers", on_delete=models.CASCADE)
	created_at = models.DateTimeField(default=timezone.now)

	class Meta:
		unique_together = ('follower', 'followed')

	def __str__(self):
		return f"{self.follower} follows {self.followed}" 

class Notification(models.Model):
	NOTIFICATION_TYPES = (
		('like', 'Like'),
		('follow', 'Follow'),
	)
	recipient = models.ForeignKey(User, related_name='notifications', on_delete=models.CASCADE)
	sender = models.ForeignKey(User, related_name='sender_notifications', on_delete=models.CASCADE)
	notification_type = models.CharField(choices=NOTIFICATION_TYPES, max_length=10)
	post = models.ForeignKey(blog_models.Post, null=True, blank=True, on_delete=models.CASCADE)
	timestamp = models.DateTimeField(default=timezone.now)
	is_read = models.BooleanField(default=False)

	def __str__(self):
		return f"{self.sender} {self.notification_type} {self.recipient}"

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
  email = forms.EmailField()
  
  class Meta:
  	model = User
  	fields = ['username', 'email', 'password1', 'password2']

class  UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		"""docstring for Meta"""
		model = User
		fields = ['username', 'email']

			
class ProfileUpdateForm(forms.ModelForm):
	bio = forms.CharField(
		widget=forms.Textarea(
			attrs={
				'class': 'form-control',
				'placeholder': 'Tell us about you....',
				'rows': 2,
			}
		),
		required=False,
	)
	class Meta:
		model = Profile
		fields = ['bio', 'image']
		
			

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from blog import models as blog_models
from django.contrib import messages
from .models import Profile, Follow, Notification
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Account successfully created for { username }! You can Login now.')
                return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})
    
@login_required   
def profile(request):
    user_profile = request.user
    followers = Follow.objects.filter(followed=user_profile).select_related('follower')
    following = Follow.objects.filter(follower=user_profile).select_related('followed')
    followers_count = Follow.objects.filter(followed=user_profile).count()
    following_count = Follow.objects.filter(follower=user_profile).count()
    post_count = blog_models.Post.objects.filter(author=user_profile).count()
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Profile updated!')
            return redirect('my_profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'user_profile': user_profile,
        'followers': followers,
        'following': following,
        'followers_count': followers_count,
        'following_count': following_count,
        'post_count': post_count
    }
    return render(request, 'users/my-profile.html', context)

def user_profile(request, username):
    user_profile = get_object_or_404(User, username=username)
    followers_count = Follow.objects.filter(followed=user_profile).count()
    following_count = Follow.objects.filter(follower=user_profile).count()
    post_count = blog_models.Post.objects.filter(author=user_profile).count()
    is_following = False
    if request.user.is_authenticated:
        is_following = Follow.objects.filter(follower=request.user, followed=user_profile).exists()

    context = {
        'user_profile': user_profile,
        'is_following': is_following,
        'followers_count': followers_count,
        'following_count': following_count,
        'post_count': post_count,
    }
    return render(request, 'users/profile.html', context)


@login_required
def follow_user(request, username):
    user_to_follow = get_object_or_404(User, username=username)
    user = request.user
    if user_to_follow != request.user:
        follow, created = Follow.objects.get_or_create(follower=user, followed=user_to_follow)
        if created:
            if not Notification.objects.filter(recipient=user_to_follow, sender=user, notification_type='follow').exists():
                Notification.objects.create(
                    recipient=user_to_follow,
                    sender=user,
                    notification_type='follow',
                )
            return JsonResponse({'status': 'followed'})
        else:
            follow.delete()
            return JsonResponse({'status': 'unfollowed'})
    return JsonResponse({'status': 'error'})


def followers_following(request, username):
    # Get the user whose profile is being viewed
    user_profile = get_object_or_404(User, username=username)
    
    # Get followers and following lists
    followers = Follow.objects.filter(followed=user_profile).select_related('follower')
    following = Follow.objects.filter(follower=user_profile).select_related('followed')
    
    context = {
        'user_profile': user_profile,
        'followers': followers,
        'following': following,
        'tab': request.GET.get('tab', 'followers'),  # Default to 'followers' tab if no tab is specified
    }
    return render(request, 'users/followers_following.html', context)

@login_required
def notifications(request):
    notifications = request.user.notifications.all().order_by('-timestamp')
    context = {'notifications': notifications}
    return render(request, 'users/notifications.html', context)

users/templates/users/followers_following.html
{% extends "blog/base.html" %}
{%load crispy_forms_tags %}
{% block content %}

<div class="container">

    <!-- Tab navigation -->
    <div class="tabs">
        <a href="?tab=followers" class="{% if tab == 'followers' %}active-tab{% endif %}">Followers</a>
        <a href="?tab=following" class="{% if tab == 'following' %}active-tab{% endif %}">Following</a>
    </div>

    <!-- Followers List -->
    <div class="tab-content {% if tab == 'followers' %}active{% endif %}">
        <ul class="profile-list">
            {% for follow in followers %}
                <li>
                    <img src="{{ follow.follower.profile.image.url }}" alt="{{ follow.follower.username }}" class="profile-picture">
                    <div class="profile-info">
                        <a href="{% if follow.follower == request.user %}{% url 'my_profile' %}{% else %}{% url 'profile' follow.follower.username %}{% endif %}">
                            {{ follow.follower.username }}
                        </a>
                        <span>{{ follow.follower.email }}</span>
                    </div>
                </li>
            {% empty %}
                <li>No followers yet.</li>
            {% endfor %}
        </ul>
    </div>

    <!-- Following List -->
    <div class="tab-content {% if tab == 'following' %}active{% endif %}">
        <ul class="profile-list">
            {% for follow in following %}
                <li>
                    <img src="{{ follow.followed.profile.image.url }}" alt="{{ follow.followed.username }}" class="profile-picture">
                    <div class="profile-info">
                        <a href="{% if follow.followed == request.user %}{% url 'my_profile' %}{% else %}{% url 'profile' follow.followed.username %}{% endif %}">
                            {{ follow.followed.username }}
                        </a>
                        <span>{{ follow.followed.email }}</span>
                    </div>
                </li>
            {% empty %}
                <li>Not following anyone yet.</li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock content %}

users/templates/users/login.html
{% extends "blog/base.html" %}
{%load crispy_forms_tags %}
{% block content %}
    <div class="content-section" style="justify-content: center; text-align: center;">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                {{ form|crispy }}
            </fieldset>
            <div>
            <small class="text-muted">
                <a href="{% url 'password_reset' %}">Forgot Password?</a>
            </small>
            </div>
            <div class="form-group" >
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="or-divider">or</div>
        {% load socialaccount %}
        <a href="{% provider_login_url 'google' %}?process=login" class="google-button">
            <img src="https://www.google.com/favicon.ico" alt="Google logo" width="20" height="20">
            Continue with Google
        </a>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an account? <a class="ml-2" href="{% url 'register' %}">Sign Up</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "blog/base.html" %}
{% block content %}
   <h2>You are logged out</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a class="ml-2" href="{% url 'login' %}">Login</a>
            </small>
        </div>
{% endblock content %}

users/templates/users/my-profile.html
{% extends "blog/base.html" %}
{%load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
    <div class="media">
            <img id="profileImage" src="{{ user.profile.image.url }}" class="rounded-circle account-img" alt="Profile Image" >
            
        <div class="media-body" >
<div class="row text-center mb-3" style="margin-top: 30px;">
    <div class="col">
            <span class="fw-bold">{{ followers_count }}</span>
            <p><a href="{% url 'followers_following' user.username %}?tab=followers" class="mr-2">Followers</a></p>
        </div>
        <div class="col">
            <span class="fw-bold">{{ following_count }}</span>
            <p><a href="{% url 'followers_following' user.username %}?tab=following" class="mr-2">Following</a></p>
        </div>
        <div class="col">
            <span class="fw-bold">{{ post_count }}</span>
            <p><a href="{% url 'user-posts' user.username %}" class="mr-2">Posts</a></p>
        </div>
    </div>
</div>
    </div>
    <div style="margin-left: 20px;">
    <h3 class="account-heading">{{ user.username }}</h3>
            <p class="text-secondary">{{ user.email }}</p>
            <p>{{ user.profile.bio }}</p>
    </div>
    <div class="col-md-8">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <legend class="border-bottom mb-4">Profile Info</legend>
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username" value="{{ user.username }}" required>
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}" required>
            </div>
            <div class="form-group">
                <label for="id_bio">Bio</label>
                <input type="text" class="form-control" id="bio" name="bio" value="{{ user.profile.bio }}">
            </div>
            <div class="form-group">
            <input type="file" id="imageUpload" name="image" accept="image/*" class="form-control-file mt-3" style="display: none;" onchange="previewImage(event)">
            <button type="button" class="change-prof" onclick="document.getElementById('imageUpload').click();">
                Change Profile Picture
            </button>
            </div>
        
            <button type="submit" class="btn btn-outline-info">Update Profile</button>
        </form>
    </div>
    </div>
    <script>
        function previewImage(event) {
            const reader = new FileReader();
            reader.onload = function(){
                const output = document.getElementById('profileImage');
                output.src = reader.result;
            }
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>

{% endblock content %}

users/templates/users/notifications.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container">
    <h2>Notifications</h2>
    <ul class="profile-list">
        {% for notification in notifications %}
            <li class="notification-item">
                <div class="notification-content">
                    <img src="{{ notification.sender.profile.image.url }}" alt="{{ notification.sender.username }}'s profile picture" class="profile-picture">
                    <div class="notification-text">
                        {% if notification.notification_type == 'like' %}
                            <a href="{% url 'profile' notification.sender.username %}">{{ notification.sender.username }}</a> liked your post.
                        {% elif notification.notification_type == 'follow' %}
                            <a href="{% url 'profile' notification.sender.username %}">{{ notification.sender.username }}</a> followed you.
                        {% else %}
                            Unknown notification type.
                        {% endif %}
                    </div>
                </div>
                <div class="timestamp">{{ notification.timestamp }}</div>
            </li>
        {% empty %}
            <li class="notification-item">No new notifications.</li>
        {% endfor %}
    </ul>
</div>

{% endblock content %}

users/templates/users/password_reset.html
{% extends "blog/base.html" %}
{%load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "blog/base.html" %}
{% block content %}
   <div class="alert alert-info">
    Your password has been set.
   </div>
   <a href="{% url 'login' %}">Log In</a>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "blog/base.html" %}
{%load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "blog/base.html" %}
{% block content %}
   <div class="alert alert-info">
    An email with instructions to reset your password has been sent.
   </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "blog/base.html" %}
{%load crispy_forms_tags %}
{% block content %}

<div class="container d-flex justify-content-center align-items-center">
        <div class="content-section text-center shadow" style="width: 24rem;">
            <div class="profile-image mt-3">
                <img src="{{ user_profile.profile.image.url }}" alt="Profile Picture" class="rounded-circle img-fluid border" style="width: 130px; height: 130px;">
            </div>
            <div class="card-body">
                <h4 class="card-title">{{ user_profile.username }}</h4>
                <p class="text-muted">{{ user_profile.email }}</p>
                <p class="fw-bold">{{ user_profile.profile.bio }}</p>
                <div class="row text-center mb-3">
                    <div class="col">
                        <span class="fw-bold">{{ followers_count }}</span>
                        <p><a href="{% url 'followers_following' user_profile.username %}?tab=followers" class="mr-2">Followers</a></p>
                    </div>
                    <div class="col">
                        <span class="fw-bold">{{ following_count }}</span>
                        <p><a href="{% url 'followers_following' user_profile.username %}?tab=following" class="mr-2">Following</a></p>
                    </div>
                    <div class="col">
                        <span class="fw-bold">{{ post_count }}</span>
                        <p><a href="{% url 'user-posts' user_profile.username %}" class="mr-2">Posts</a></p>
                    </div>
                </div>
                <div class="d-flex justify-content-around mb-3">
                    {% if user != user_profile %}
                  <button id="follow-btn" data-username="{{ user_profile.username }}" class="connect-btn">
                       {% if is_following %}
                          Unfollow
                      {% else %}
                        Follow
                      {% endif %}
                  </button>
                  {% endif %}
                  <a href="{% url 'chat' user_profile.id %}" class="chat-link">Chat with {{ user_profile.username }}</a>
                </div>
            </div>
        </div>
    </div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $('#follow-btn').click(function() {
            var button = $(this);
            var username = button.data('username');
    
            $.ajax({
                url: "{% url 'follow_user' 'dummy_username' %}".replace('dummy_username', username),
                method: 'POST',
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                },
                success: function(response) {
                    if (response.status === 'followed') {
                        button.text('Unfollow');
                    } else if (response.status === 'unfollowed') {
                        button.text('Follow');
                    }
                }
            });
            
        });
    });
    </script>
{% endblock content %}

users/templates/users/register.html
{% extends "blog/base.html" %}
{%load crispy_forms_tags %}
{% block content %}
    <div class="content-section" style="justify-content: center; text-align: center;">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="or-divider">or</div>
        {% load socialaccount %}
        <a href="{% provider_login_url 'google' %}?process=login" class="google-button">
            <img src="https://www.google.com/favicon.ico" alt="Google logo" width="20" height="20">
            Continue with Google
        </a>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}